// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CocktailRecipe
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("filteredOn")]
        public string FilteredOn { get; set; }

        [JsonProperty("cocktails")]
        public Cocktail[] Cocktails { get; set; }
    }

    public partial class Cocktail
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("glass")]
        public string Glass { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("ingredients")]
        public Ingredient[] Ingredients { get; set; }

        [JsonProperty("preparation")]
        public string Preparation { get; set; }

        [JsonProperty("garnish", NullValueHandling = NullValueHandling.Ignore)]
        public string Garnish { get; set; }
    }

    public partial class Ingredient
    {
        [JsonProperty("unit", NullValueHandling = NullValueHandling.Ignore)]
        public Unit? Unit { get; set; }

        [JsonProperty("amount", NullValueHandling = NullValueHandling.Ignore)]
        public double? Amount { get; set; }

        [JsonProperty("ingredient", NullValueHandling = NullValueHandling.Ignore)]
        public string IngredientIngredient { get; set; }

        [JsonProperty("label", NullValueHandling = NullValueHandling.Ignore)]
        public string Label { get; set; }

        [JsonProperty("special", NullValueHandling = NullValueHandling.Ignore)]
        public string Special { get; set; }
    }

    public enum Unit { Cl };
}
